### ISSUE TITLE
Issue when logging in some php versions.

### ISSUE THREAD

**Issue by wiliame** [eyecatchup/GWT_CrawlErrors-php#1]
Hi, the class in some cases doesn't work, CURLOPT_POSTFIELDS doesn't accepts array as parameter in all versions of php.

http://php.net/manual/en/function.curl-setopt.php

To fix the array must be converted to a string before:

```
        $tmp = array();
        foreach($postRequest as $key => $value) {
            $tmp[] = $key . '=' . rawurlencode($value);
        }
        $requestStr = implode('&', $tmp);
```

**Comment by eyecatchup** [comment]
I don't see where PHP doesn't accept arrays when I read the manual. Actually, it says **"This parameter can either be passed as a urlencoded string"** snip **"or as an array."** And **"as of PHP 5.2.0, value must be an array"**

However, "fixed" in https://github.com/eyecatchup/GWT_CrawlErrors-php/commit/5eb63d242d2ad1f2e39aa4bb92022c745fb727ce (since I know that some PHP installations just won't work with arrays and I know that all version above 5.2.0 can handle arrays).
